package listthingsbot.telegrambot.actions.callbackqueries;

import listthingsbot.telegrambot.Chat;
import listthingsbot.telegrambot.actions.Action;

import java.util.HashMap;
import java.util.Map;

/**
 * Every time the user send a valid Callback query from Telegram an instance of this class is executed
 */
public abstract class CallbackQuery extends Action
{
	/**
	 * The Telegram CallbackQuery object generated by the user
	 */
	protected org.telegram.telegrambots.meta.api.objects.CallbackQuery telegramCallbackQuery;

	public CallbackQuery(Chat c, org.telegram.telegrambots.meta.api.objects.CallbackQuery telegramCallbackQuery)
	{
		super(c);
		this.telegramCallbackQuery = telegramCallbackQuery;
	}

	/**
	 * This method is used to create the right CallbackQuery object based on a String
	 *
	 * @param telegramCallbackQuery the Telegram CallbackQuery object created when the user pushed the button
	 * @param chat  the chat where the callback query is invoked
	 * @return the right CallbackQuery object based on the commandName string
	 */
	public static CallbackQuery getCallbackQuery(org.telegram.telegrambots.meta.api.objects.CallbackQuery telegramCallbackQuery, Chat chat)
	{
		Map<String, CallbackQuery> actions = new HashMap<>();

		actions.put("lists", new ShowLists(chat, telegramCallbackQuery));
		actions.put("show", new ShowList(chat, telegramCallbackQuery));
		actions.put("delete", new DeleteList(chat, telegramCallbackQuery));
		actions.put("rename", new RenameList(chat, telegramCallbackQuery));
		actions.put("additems", new AddItemsToList(chat, telegramCallbackQuery));
		actions.put("removeitem", new RemoveItemFromList(chat, telegramCallbackQuery));

		String value = telegramCallbackQuery.getData().split("_")[0];

		return actions.get(value);
	}
}
